spring:
  config:
    activate:
      on-profile: prod
  data:
    mongodb:
      uri: "${SPRING_DATA_MONGODB_URI}"
  datasource:
    url: "${SPRING_DATASOURCE_URL}"
    username: "${POSTGRES_USER}"
    password: "${POSTGRES_PASSWORD}"

jwt:
  secret: "${JWT_SECRET}"
  expiration: "${JWT_EXPIRATION:3600000}"