spring:
  config:
    activate:
      on-profile: dev
  devtools:
    add-properties: true
  data:
    mongodb:
      uri: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@${MONGO_HOST:localhost}:27017/${MONGO_DB:chatdb}?authSource=admin
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:5432/${POSTGRES_DB:postgres}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: update
  sendgrid:
    api-key: ${SENDGRID_KEY}
    from-email: ${FROM_EMAIL}
    otp: ${TEMPLATE_OTP_ID}
    expiration-minutes: 5

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

openapi:
  service:
    api-docs: backend
    title: Backend API document
    version: v1.0.0
    server: http://localhost:${server.port}

jwt:
  secret-key-access: ${JWT_SECRET_ACCESS}
  secret-key-refresh: ${JWT_SECRET_REFRESH}
  expiry-minutes: 60
  expiry-day: 7