spring:
  config:
    activate:
      on-profile: test
  data:
    mongodb:
      uri: "${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/chatdb_test?authSource=admin}"

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

openapi:
  service:
    api-docs: backend
    title: Backend API (Test Env)
    version: v1.0.0
    server: ${SERVER_URL:http://localhost:${server.port}}

jwt:
  secret: ${JWT_SECRET_TEST}
  expiration: 3600000